#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
codex_root="${CODEX_HOME:-$HOME/.codex}"
opencode_root="${XDG_CONFIG_HOME:-$HOME/.config}/opencode"
copilot_mcp_config="$HOME/.copilot/mcp-config.json"
vscode_user_settings="$HOME/Library/Application Support/Code/User/settings.json"

required_files=(
  "$codex_root/AGENTS.md"
  "$codex_root/config.toml"
  "$codex_root/agents/worker.toml"
  "$codex_root/agents/tester.toml"
  "$codex_root/agents/planner.toml"
  "$codex_root/agents/reviewer.toml"
  "$opencode_root/AGENTS.md"
  "$opencode_root/opencode.json"
)

for required_file in "${required_files[@]}"; do
  if [[ ! -f "$required_file" ]]; then
    echo "Missing required configuration: $required_file" >&2
    exit 1
  fi
done

python3 - "$codex_root/config.toml" "$repo_root/config.example.toml" <<'PY'
import pathlib
import re
import sys

source_path = pathlib.Path(sys.argv[1])
target_path = pathlib.Path(sys.argv[2])
source = source_path.read_text()

def setting(name, section=None):
    current_section = None
    for raw_line in source.splitlines():
        line = raw_line.strip()
        section_match = re.fullmatch(r"\[([^]]+)\]", line)
        if section_match:
            current_section = section_match.group(1)
            continue
        if current_section != section:
            continue
        match = re.fullmatch(rf"{re.escape(name)}\s*=\s*(.+)", line)
        if not match:
            continue
        value = match.group(1).strip()
        if len(value) >= 2 and value[0] == value[-1] == '"':
            return value[1:-1]
        if re.fullmatch(r"[0-9]+", value):
            return int(value)
        raise SystemExit(f"Unsupported value for {name}: {value}")
    return None

required = {
    "model": setting("model"),
    "model_reasoning_effort": setting("model_reasoning_effort"),
    "personality": setting("personality"),
    "max_concurrent_threads_per_session": setting("max_concurrent_threads_per_session", "agents"),
    "default_subagent_model": setting("default_subagent_model", "agents"),
    "default_subagent_reasoning_effort": setting("default_subagent_reasoning_effort", "agents"),
}
missing = [key for key, value in required.items() if value is None]
if missing:
    raise SystemExit(f"Missing portable Codex settings: {', '.join(missing)}")

target_path.write_text(
    "# Generated by scripts/sync-local-ai-setup.sh.\n"
    "# Merge these portable settings into ~/.codex/config.toml. Keep credentials, local paths,\n"
    "# MCP environment values, and machine-specific application settings only in local config.\n\n"
    f'model = "{required["model"]}"\n'
    f'model_reasoning_effort = "{required["model_reasoning_effort"]}"\n'
    f'personality = "{required["personality"]}"\n'
    'approval_policy = "on-request"\n'
    'sandbox_mode = "workspace-write"\n\n'
    "[agents]\n"
    f'max_concurrent_threads_per_session = {required["max_concurrent_threads_per_session"]}\n'
    f'default_subagent_model = "{required["default_subagent_model"]}"\n'
    f'default_subagent_reasoning_effort = "{required["default_subagent_reasoning_effort"]}"\n'
)
PY

python3 - "$opencode_root/opencode.json" <<'PY'
import json
import pathlib
import re
import sys

path = pathlib.Path(sys.argv[1])
config = json.loads(path.read_text())
sensitive = re.compile(r"(?:api[_-]?key|authorization|credential|password|secret|token)", re.I)
sensitive_value = re.compile(
    r"(?:sk-[A-Za-z0-9_-]{20,}|ghp_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|"
    r"AKIA[0-9A-Z]{16}|-----BEGIN [A-Z ]*PRIVATE KEY-----|Bearer [A-Za-z0-9._-]{20,})"
)

def walk(value, parts=()):
    if isinstance(value, dict):
        for key, child in value.items():
            next_parts = (*parts, str(key))
            if sensitive.search(str(key)):
                raise SystemExit(f"Credential-like OpenCode key found: {'.'.join(next_parts)}")
            walk(child, next_parts)
    elif isinstance(value, list):
        for index, child in enumerate(value):
            walk(child, (*parts, str(index)))
    elif isinstance(value, str) and sensitive_value.search(value):
        raise SystemExit(f"Credential-like OpenCode value found: {'.'.join(parts)}")

walk(config)
PY

install -m 0644 "$codex_root/AGENTS.md" "$repo_root/AGENTS.md"
for role in worker tester planner reviewer; do
  install -m 0644 "$codex_root/agents/$role.toml" "$repo_root/agents/$role.toml"
done
install -m 0644 "$opencode_root/AGENTS.md" "$repo_root/opencode/AGENTS.md"
install -m 0644 "$opencode_root/opencode.json" "$repo_root/opencode/opencode.json"

mkdir -p "$repo_root/agents/router"
shopt -s nullglob
router_tomls=("$codex_root/agents/router-model-"*.toml)
shopt -u nullglob
if (( ${#router_tomls[@]} )); then
  grep -riE "api[_-]?key|secret|token|password|authorization" "${router_tomls[@]}" >/dev/null && {
    echo "Credential-like string found in Codex Router agent definitions" >&2
    exit 1
  } || true
  for toml in "${router_tomls[@]}"; do
    install -m 0644 "$toml" "$repo_root/agents/router/$(basename "$toml")"
  done
  echo "Mirrored ${#router_tomls[@]} Codex Router agent definitions."
fi

python3 - "$copilot_mcp_config" "$repo_root/copilot/mcp-config.example.json" <<'PY'
import json
import pathlib
import re
import sys

source = pathlib.Path(sys.argv[1])
target = pathlib.Path(sys.argv[2])
config = json.loads(source.read_text())
for server in config.get("mcpServers", {}).values():
    command = server.get("command")
    if isinstance(command, str):
        server["command"] = pathlib.PurePath(command).name
text = json.dumps(config, indent=2) + "\n"
if re.search(r"(?:api[_-]?key|authorization|credential|password|secret|token)", text, re.I):
    raise SystemExit("Credential-like string found in Copilot MCP configuration")
target.write_text(text)
PY

python3 - "$vscode_user_settings" "$repo_root/vscode/settings.example.json" <<'PY'
import json
import pathlib
import re
import sys

source = pathlib.Path(sys.argv[1])
target = pathlib.Path(sys.argv[2])
config = json.loads(source.read_text())
text = json.dumps(config, indent=4) + "\n"
if re.search(r"(?:api[_-]?key|authorization|credential|password|secret|token)", text, re.I):
    raise SystemExit("Credential-like string found in VS Code settings")
target.write_text(text)
PY

third_party_skills=(
  changelog-generate ci-pipeline code-review codebase-design dependency-audit
  diagnosing-bugs domain-modeling git-release grill-with-docs implement
  improve-codebase-architecture prototype research resolving-merge-conflicts
  setup-matt-pocock-skills tdd test-patterns to-spec to-tickets triage wayfinder wizard
)
unmirrored="$(comm -23 \
  <(ls "$opencode_root/skill" | sort) \
  <(ls "$repo_root/opencode/skill" | sort))"
drift=""
while IFS= read -r skill; do
  [[ -z "$skill" ]] && continue
  is_third_party=0
  for known in "${third_party_skills[@]}"; do
    [[ "$skill" == "$known" ]] && { is_third_party=1; break; }
  done
  if (( ! is_third_party )); then
    drift+="$skill "
  fi
done <<< "$unmirrored"
if [[ -n "$drift" ]]; then
  echo "Unmirrored OpenCode skills are not third-party references: $drift" >&2
  exit 1
else
  echo "OpenCode skills drift check passed."
fi

python3 - "$repo_root" <<'PY'
import json
import pathlib
import re
import sys

root = pathlib.Path(sys.argv[1])
portable_config = (root / "config.example.toml").read_text()
for required_key in (
    "model",
    "model_reasoning_effort",
    "personality",
    "max_concurrent_threads_per_session",
    "default_subagent_model",
    "default_subagent_reasoning_effort",
):
    if not re.search(rf"(?m)^{re.escape(required_key)}\s*=", portable_config):
        raise SystemExit(f"Missing portable setting: {required_key}")
for path in sorted((root / "agents").glob("*.toml")):
    agent = path.read_text()
    for required_key in ("name", "description", "model", "model_reasoning_effort", "developer_instructions"):
        if not re.search(rf"(?m)^{re.escape(required_key)}\s*=", agent):
            raise SystemExit(f"Missing {required_key} in {path}")
    if agent.count('"""') % 2:
        raise SystemExit(f"Unbalanced multiline string in {path}")
router_agents = sorted((root / "agents" / "router").glob("*.toml")) if (root / "agents" / "router").is_dir() else []
for path in router_agents:
    agent = path.read_text()
    for required_key in ("name", "description", "model_provider", "model", "developer_instructions"):
        if not re.search(rf"(?m)^{re.escape(required_key)}\s*=", agent):
            raise SystemExit(f"Missing {required_key} in {path}")
    if re.search(r"(?mi)api[_-]?key|secret|token|password|authorization", agent):
        raise SystemExit(f"Credential-like string in {path}")
    if agent.count('"""') % 2:
        raise SystemExit(f"Unbalanced multiline string in {path}")
json.loads((root / "opencode/opencode.json").read_text())
json.loads((root / "copilot/mcp-config.example.json").read_text())
json.loads((root / "vscode/settings.example.json").read_text())
print(
    f"Validated portable Codex and OpenCode configuration "
    f"({len(router_agents)} Codex Router agents, Copilot MCP, VS Code settings)."
)
PY

echo "Synchronized portable configuration into $repo_root"
echo "Review with: git -C $repo_root status --short && git -C $repo_root diff"
